### ISSUE TITLE
stack level too deep on session dump.

### ISSUE THREAD

**Issue by acarpe** [github/view_component#1127]
Starting from ver. 2.35.0 I'm getting a `SystemStackError stack level too deep`.
after rendering the view, the user session is stored in the session storage (a `RedisSessionStore` in my case)

with the 2.34.0 the session contains a key for the rendered view like this one:
<img width="703" alt="Schermata 2021-11-08 alle 15 48 00" src="https://user-images.githubusercontent.com/179885/140763152-2acf32f4-ed4f-41a7-87e1-7ec1e331bda0.png">

in the 2.35.0 the key is changed in this way:
<img width="894" alt="Schermata 2021-11-08 alle 15 13 37" src="https://user-images.githubusercontent.com/179885/140763475-247c22d8-8c31-4f70-aceb-0f62a8223569.png">

basically renaming `@controller` and `@helpers` fields in `@__vc_controller` and `@__vc_helpers` introduced the problem because it tries to serialize the rack `env` that contains a recursive reference to `env` itself.
the commit is this one: https://github.com/github/view_component/commit/e443c1f80afc16b65b10eae9aff046e48b8e1be6

the problem is present in the latest version too (2.43.0) because of the field variable `@original_view_context`

If, in the 2.35.0 I rename back the field variable to `@controller` and `@helpers` the Errors go away. 
I don't know this part of Rails very well but I suspect that there are some filter somewhere that exclude `@controllers` and `@helpers` to the list of fields to be serialized.

## System configuration

Rails version: 6.1.4.1

Ruby version: 3.0.1

Gem version: from 2.35.0 to 2.43.0

**Comment by boardfish** [comment]
Thanks for raising this @acarpe! I wonder if this exclusive to that type of session store. Regardless, it's clearly a blocker for you - let's see what we can do to get it fixed.

A failing test case or example repo would be really helpful - the former's preferable, but if the latter's easier, you can get started as follows:

```
rails new --minimal view_component-1127
cd view_component-1127
bundle add view_component
```

Then add the `require: 'view_component/engine'` param to `gem 'view_component'` in the Gemfile.

---

I couldn't find any code relating to a filter for serialization, but I get the feeling you might be right that something like that exists within the project. Either that or the variable is in the session because it starts with `__`.
