### ISSUE TITLE
&block calls render content twice

### ISSUE THREAD

**Issue by jamieshark** [github/view_component#1138]
### Steps to reproduce

<img width="2481" alt="Screen Shot 2021-11-15 at 2 36 30 PM" src="https://user-images.githubusercontent.com/5520141/141851090-e9c63f63-be9d-4fe7-a45f-fec7343031c5.png">

1. Use `yield block` in `link_to_feed_discussion` helper
2. Provide a `block` argument when calling helper
3. Note that "Join discussion" string renders twice

### Expected behavior

"Join discussion" string should only render once

### Actual behavior

"Join discussion" string renders twice

### System configuration
**Rails version**:
"7.0.0.alpha2.016f6c8"
**Ruby version**:
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
**Gem version**:
gem "primer_view_components", "0.0.60"

**Comment by boardfish** [comment]
Shot in the dark here, but I'd wager this is happening because you're calling `yield block` instead of passing the block to `link_to` like so:

```rb
link_to("/#{repo.name_with_owner}", classes: classes, data: data, &block)
```

I think `yield block` would call and run the block, which `link_to` would internally `capture` to ensure that its output ends up inside the link tag, but since `yield` is not called, the return value of the block would not be rendered. Let me know if that works for you!

**Comment by jamieshark** [comment]
ahhh indeed. Okay, that makes sense! I ended up using a different implementation anyway, so we can probably close this issue, but that is good to know for the future. thanks!
