### ISSUE TITLE
Deprecation Warning on application load

### ISSUE THREAD

**Issue by guillaumewrobel** [github/view_component#1180]
### Expected behavior
No deprecation warning.

### Actual behavior

> DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from <top (required)> at /my_rails_app/config/application.rb:9)

with the line 9 as the default `Bundler.require`

```ruby
# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
```

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 3.0.3

**Gem version**: 2.46.0

**Comment by rmacklin** [comment]
This is the intended behavior of https://github.com/github/view_component/pull/1162, as it is no longer necessary to specify `require "view_component/engine"` in your `Gemfile` when declaring the `view_component` dependency after https://github.com/github/view_component/pull/1117. The warning is telling you to remove that part, because the plan is to remove support for that on version 3

**Comment by guillaumewrobel** [comment]
That's it. Thanks.

**Comment by rmacklin** [comment]
I think we can improve the release notes to make this clearer to anyone who is upgrading.
