### ISSUE TITLE
Supercharging Previews 

### ISSUE THREAD

**Issue by jonspalmer** [github/view_component#159]
[Storybook.js](https://storybook.js.org/) has taken off as a powerful and interactive way to document the React components in a project. The ViewComponent Previews could be enhanced to provide much the same power and allow teams to create automated "Design System" playgrounds for their server side rendered components.

Key Features to add that would make a big difference:

- Load components in and iframe - This allows someone to browse the library of components without a bunch of back and forth in the browser.
- [Knobs](https://github.com/storybookjs/storybook/tree/master/addons/knobs) - being able to dynamically alter the parameters passed to the component and seeing it live is a big win.
- [Docs](https://github.com/storybookjs/storybook/tree/master/addons/docs) - I assume we could leverage RDoc annotations or the like.

There are some other bells and whistles in [Storybook Addons](https://storybook.js.org/addons/) that we should consider. [Viewport](https://github.com/storybookjs/storybook/tree/master/addons/viewport) stands out most to me - others are much more JS focused.

**Comment by joelhawksley** [comment]
@bostanio these are all excellent suggestions. I almost wonder if we should consider similar improvements for Mailer previews as well, as that's what we modeled the existing behavior after.

**Comment by bostanio** [comment]
Agreed. The Mailer Previews a pretty bare bones IMO.

**Comment by bostanio** [comment]
I have a theory that it might be possible to leverage Storybook directly. They've recently added support for "standalone" mode where the list of stories is loaded from an external source. Perhaps we can figure out the right dsl to provide AV:Components to Storybook?

https://github.com/storybookjs/storybook/tree/next/examples/standalone-preview

**Comment by shilman** [comment]
@bostanio Standalone mode was the first step towards supporting ANY backend, with Rails in mind as the most active server-side environment. We'd love to work with somebody from the Rails community to make Storybook for Rails a reality.

As a little background:

- Standalone mode was released in [Storybook 5.2](https://medium.com/storybookjs/storybook-5-2-794958b9b111) and community members have been making use of it in other server contexts, e.g. Parcel, `es-dev-server`.
- There has been [successful experimentation](https://dev.to/open-wc/storybook-for-web-components-on-steroids-4h29) by @daKmoR of Open Web Components to statically bundle the UI so that everything can be served from an arbitrary server. This hasn't made its way back into Storybook yet, but is an active project.

Storybook's 6.0 ship window closes in two months (end of Feb), so right now would be the best time to get in any breaking changes. It's also likely that we could integrate without breaking changes in a 6.x release.

**Comment by tmeasday** [comment]
Hey, I've spend some cycles thinking about how "Storybook for Rails" could work in the past, and would be keen to get a POC going. A while back I posted some thoughts in the #server channel of Storybook's Discord, which @bostanio seems to have found.

Can continue the conversation there for the next little bit perhaps.

**Comment by bostanio** [comment]
Proof of concept of using a rails backend as the preview url for Storybook running in standalone more: https://github.com/bostanio/avc_storybook

There are a few of things we could do in AV:C to simplify that approach as well as provide meta data to support Storybook knobs

**Comment by jonspalmer** [comment]
For anyone following this I just release the first version of ViewComponent::Storybook that provides a bridge between ViewComponents previewed in Storybook: https://github.com/jonspalmer/view_component_storybook

**Comment by jaredcwhite** [comment]
@jonspalmer Oooo, I can't wait to try this out.
