### ISSUE TITLE
Any tips for rendering Components from collections?

### ISSUE THREAD

**Issue by nogtini** [github/view_component#21]
Before I start playing around with this, I wanted to ask if there is a preferred way, best practice, or even a helper to render components for collections [similar to the rails guide for partials](https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections)

I think this would be a common use case, and would be willing to submit a PR for a documentation example.

**Comment by mikker** [comment]
An idea for the API,

```ruby
<%= render MyComponent.all(collection, more_options: true) %>
```

Perhaps. But it's a tiny win over

```ruby
<% collection.each do |thing| %>
  <%= render MyComponent.all(thing, more_options: true) %>
<% end %>
```

Then again; you could say that about a lot of Rails 😆

**Comment by nogtini** [comment]
True, though I would imagine if there were to be an API it might look as similar as possible to the partial api.

### Partial
```
<h1>Products</h1>
<%= render partial: "product", collection: @products %>
```

### Component
```
<h1>Products</h1>
<%= render component: Product, collection: @products %>
```

**Comment by joelhawksley** [comment]
@nogtini I don't think I could recommend a _good_ practice here at this point, let along a _best_ practice!

Generally our approach in writing this library has been to stay consistent with Rails APIs, at least as a default. What @nogtini is suggesting is probably the direction I think we'd go in.

**Comment by joelhawksley** [comment]
@nogtini @mikker this is definitely something we'll want to consider.

Right now, we're passing an instance of the component into `render`:

```erb
<%= render MyComponent.new(product: product) %>
```

which means we've already defined what data is going to be used to render the component. 

We might have to change that syntax in order to accommodate the `collection` key. Perhaps we would do something like:

```erb
<%= render MyComponent, collection: products %>
```

Or perhaps we could support both syntaxes?

**Comment by inopinatus** [comment]
Rendering a partial collection is also blazingly fast, because Rails only instantiates each template once, and they're also polymorphic.

AV:C can't be either in it's current architecture: firstly, by using ActiveModel's validations it's obliged to instantiate every component individually, there's no flyweight-pattern option; secondly, there's no `to_partial_path`-equivalent hook to select a component by convention-over-configuration.

I work with Big Heterogeneous Lists Of Stuff and those are both showstoppers for adoption.

**Comment by nogtini** [comment]
@joelhawksley I think whichever syntax you propose people will ingest with zeal, but I think the latter is a better choice. It fits the pre-existing mental model better, adheres to convention, and provides an obvious affordance for collections.

**Comment by joelhawksley** [comment]
Let's move forward with this ❤️. PRs welcome!
