### ISSUE TITLE
Preview index actions use application layout instead of rails application layout

### ISSUE THREAD

**Issue by tchak** [github/view_component#289]
It seems that `/rails/view_components` page is rendered with "application" layout instead of "rails/application" layout. It is a problem because `RailsApplicationController` is missing methods implemented in `ApplicationController` and potentially used in the "application" layout. I checked the difference in implementation with mails preview and I can't really spot the difference.

**Comment by joelhawksley** [comment]
@juanmanuelramallo mind having a look at this one? ❤️

**Comment by juanmanuelramallo** [comment]
Hey @tchak sorry for taking so long

I don't think you actually want to use the `rails/application` layout given that most of your components will need CSS and javascript to work properly. That's why the default layout is the application layout.

Maybe, one easy way to solve your problem would be to create a dedicated layout for view_component previews. This layout should just include CSS and javascript for your components to be displayed correctly. 

Then [you can override the component preview layout](https://github.com/github/view_component#previewing-components) with your new layout.

What do you think about that?

**Comment by tchak** [comment]
hey @juanmanuelramallo. I agree about previews. I am talking about preview listing pages. There is no way to override the layout there.

**Comment by tchak** [comment]
And it would be nice if the show with the same minimal list style as mailers preview listings.

**Comment by juanmanuelramallo** [comment]
Oh I see that's true. I think we got two options then:

1. Update the gem to use rails' layout for the index of previews
2. Allow default layout configuration (not only for previews) but also for the previews index

I think the easier would be just to go with 1? What do you think?

I'll try to create a PR with this change

**Comment by tchak** [comment]
Option 1 seems good to me :+1:

**Comment by juanmanuelramallo** [comment]
Nice! That's the option I went for! Would you mind reviewing #296 pls?

**Comment by jonspalmer** [comment]
How about a third option that the PreviewController inherit from the apps ApplicationController?

**Comment by juanmanuelramallo** [comment]
Good one, but what do we gain by doing so? 

I see a few scenarios where this might be problematic, for instance: 
- using Devise, it's common to have a `before_action :authenticate_user!` in the application controller, so if we inherit the previews controller from that controller, all the preview views will be accessible only for authenticated users 🤷 
- using Pundit, it's common to have a `after_action :verify_authorized`, and given the previews controller doesn't call Pundit's `authorize` method, the controller actions would raise an error

Maybe there are more scenarios where this might not be helpful. What are you thoughts on this?

**Comment by jonspalmer** [comment]
Testing Components and Previews already assume the existence of an ApplicationController and we provided configuration to allow you to customize it #184. I suspect testing components and Previews don't run a full controller action, they just use a controller instance to render the component html and therefore don't fall foul of before actions. 

My thought would be to use a configuration like that and use it as the base class of the ViewComponentsController.

**Comment by juanmanuelramallo** [comment]
Oh I see what you mean.

I don't think it's really necessary to allow users to set a parent controller for the previews. In fact, action mailer's previews don't do that. They just render the list of previews defined by the app, and when rendering a given preview they set the layout to `false`. 

In our case, instead of using no layout we use the application's one by default.

For the index view we were not entirely following what action mailer does, with the change proposed in #296 we now do.

I feel like adding a configuration option to allow users to set the parent controller of previews will complicate things for the final user, don't you think?

**Comment by jonspalmer** [comment]
Yeah I think I agree with you just trying to talk through the options. I wish we could make the fix a bit more intuitive.

**Comment by juanmanuelramallo** [comment]
I think there's a potential refactoring we can make. Given we are now using the `app` folder, maybe we should also move the previews templates there, to the `app/views` folder. By doing so we might no even need to call `render` in the controller, we would just let rails do its job. But I would tackle that in a subsequent PR, given is not entirely related to this issue.

**Comment by jonspalmer** [comment]
I can confirm that the approach of moving the views to `app/views` works. I just did exactly that in a different but related gem. It's much cleaner that way. Can we make that change first and reevaluate how things look after that?

On that topic it's also strange to me that we namespace these controllers with "Rails". I think we're pattern matching off ActionMailer previews but we probably shouldn't.

**Comment by juanmanuelramallo** [comment]
I totally agree with moving the view to `app/views`. But do you think by doing so we will solve this issue? 

I think there are two different issues, one is #289 the index views using the application's layout instead of the rails internal layout, and the other one is refactoring the preview templates so that they live inside `app/views. 

Regarding the namespace of the controller, that's true. We don't need to do that anymore. We started doing so because we wanted to clone action mailer's previews. So that rails core team would be on board with upstreaming this gem into rails, but since that's not a goal anymore, we can also change it to not be namespaced by `Rails`. 

I would rather move forward one step at a time, I think we can solve this issue with #296 and come back later and work on a refactor for the previews controller and templates, what do you think?

**Comment by jonspalmer** [comment]
Fair enough. Perhaps we just take this as is.

**Comment by jonspalmer** [comment]
Can we add code comments to explain the logic we want?

The other thing that tripped me up reading this change was that there is both class and instance versions of of `prepend_view_path` It would be great to add a test case that they work as expected. That is a) call the preview index b) call a preview c) call preview index and validate that the right layout is still applied. That is that the call in b) doesn't change state on the ViewComponentsController. You should be able to make that test case fail by calling the class version of `prepend_view_path` in the `preview` action

**Comment by juanmanuelramallo** [comment]
Let's move the discussion to the pull request #296
