### ISSUE TITLE
Overriding inherited partials

### ISSUE THREAD

**Issue by awead** [github/view_component#411]
### Steps to reproduce

When inheriting view component from another Rails gem, I was expecting to be able to override a component's partial in my local app. For example:

Given:

`[gem_home]/app/components/some_component.html.erb`

A local file with the same name and location:

`app/components/some_component.html.erb`

Would replace/override the content of the gem's partial.

### Expected behavior

I was expecting what Rails does with other types such as views, and replace/override the content of the gem's partial.

### Actual behavior

It doesn't seem to. I can sub-class the gem's component Ruby class and write my own partial, which is fine, but I'm wondering if this is a bug and we should _expect_ overriding things the way we typically to with other things.

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.6p146

**Gem version**: 2.14.0

**Comment by joelhawksley** [comment]
@awead thanks for taking the time to file this issue! I'm wondering what others might think about the right conventions/techniques for achieving this goal.

Can you provide an example of the gem you're working with, and what you're trying to do by replacing the component's template with your own?

**Comment by jonspalmer** [comment]
I'm curious about the examples of other places where you can just replace the view? I'm don't remember seeing that. I'm also not sure I understand the use case of subclassing the component but also replacing the gem components view file. I would expect you to want one or the other. 

Remember that Rails does view looking/path resolution by convention based on the path derived from the namespace and class name of the Controller or in our case Component. 

So if you have a gem like

[gem_home]/app/components/some_component.rb
[gem_home]/app/components/some_component.html.erb

You subclass it as:

/app/components/subclassed_some_component.rb

then the view would expect to be: 

/app/components/subclassed_some_component.html.erb

IMO it would be a bit strange to change any of that as its pretty fundamental to how Rails apps work.

**Comment by awead** [comment]
Hi all, sorry for the delayed response, and thanks for the input. Here's a link to a commit that I made in the repo I'm trying to do the override in:

https://github.com/psu-stewardship/scholarsphere-4/commit/21b331375edb9fe42a054eaa4e3961430cca5b66

The Blacklight gem has the file `app/components/blacklight/constraint_layout_component.html.erb`. I'm placing a modified variant of this file in the same relative path and it's not getting picked up.

I know for sure I can do these sorts of things in `app/views`. I think it's part of the controller's wiring to look through inherited paths to different views.

I'm guessing that a view component's Ruby class isn't doing that same kind of inheritance dance that a controller does. I can definitely override the gem's component _Ruby_ class, though.

One thing I haven't tried is overriding _both_ the Ruby class and the view...

**Comment by joelhawksley** [comment]
@jcoyne you're involved with Blacklight, right? What do you think is the right approach for us to take here?

**Comment by cdmo** [comment]
Controllers have to be open classed or subclassed if you want to modify their behavior, but their partial (View) can just be overridden via path lookup in your app. 

ViewComponents have to be open classed or sublcassed if you want to modify their behavior OR their partial.

I can see how the pattern with controllers/models and their associated views might setup an expectation that you could override _just the partial_ by being present in the path.

So let's say I want to change a single tag in an inherited engine's `ViewComponent` template. I'd rather have a `<span>` instead of `<div>` or something like that. In that case I'd create an ViewComponent that was empty save for subclassing the original component and then I could create a partial that changed the markup in the template? Is that how overriding just the template would work?

**Comment by jcoyne** [comment]
@joelhawksley sorry, I just saw this mention.  I think @awead was on the right track.  Typically Rails looks through a list of search paths until it finds a partial.   The application directory are in the front of of the list and the gem paths are at the back of this list, so the application views always get preference over any in the gem.    I think it would be easiest for new adopters if view_component also used this way, however there's a likely performance penalty there.

**Comment by joelhawksley** [comment]
@jcoyne @awead @cdmo Feel free to reopen if you'd like to take this on! I'd love to see a PR with a suggested API/example case you'd expect to work ❤️

**Comment by coorasse** [comment]
Overriding also the component works...but is quite nasty. I am trying to figure out how to path this behaviour but I am bit lost...

**Comment by marlo-longley** [comment]
I wanted to add some findings on this that I recently encountered in case it helps anybody. I was able to override the view component partial with a few steps and using the subclassing approach suggested by @cdmo above. Here's what I did to override `app/components/blacklight/search_bar_component.html.erb`:
1. Make a simple subclass of the Blacklight component in my local app at `app/components/dlme_search_bar_component.rb` with the following code:
```ruby
class DlmeSearchBarComponent < Blacklight::SearchBarComponent 
end
```

2.  Edit the accompanying partial at `app/components/dlme_search_bar_component.html.erb` to reflect my HTML changes.

3. Then, I have to tell my local app to find the new `DlmeSearchBarComponent` rather than Blacklight's. This works like a more typical view override. In `app/views/catalog/_search_form.html.erb` I replaced the class reference
```ruby 
<%= render(Blacklight::SearchBarComponent.new( ... )) %>
```
with
```ruby
<%= render(DlmeSearchBarComponent.new( ... )) %>
```

After adding these 3 files to my local app, my changes were reflected.

**Comment by barmintor** [comment]
FWIW, I prototyped the two approaches (a Compiler change, a change to _sidecar_files) mentioned here in this commit (for an engine that uses ViewComponent): https://github.com/barmintor/blacklight/commit/3b834bc5e1e51531a0ecb70b0db350bc5c057a47

In a pinch, I think you could monkey-patch components to get this behavior. I think if you want to be able to add sidecar files in a downstream app, you need the _sidecar_files override.
