### ISSUE TITLE
How should components be cached?

### ISSUE THREAD

**Issue by pinzonjulian** [github/view_component#42]
Hi! I'm starting to use components for a big project at my company and I absolutely love them. 
 Thanks for open sourcing this! 

I have some usage questions that ultimately relate to caching.

By the examples in @joelhawksley 's talk at RailsConf and the examples in the repo, I understood that the arguments you pass to your component should be as lean as possible. I infer it wouldn't be a good practice to pass entire objects (please correct me if I'm getting it wrong).

For example, if I have a message class:
```ruby
Class Message < ApplicationRecord
  # body
  # status 
  ...
end
```

To render it, I created the following component
```ruby
Class MessageComponent < ApplicationComponent
  def initialize(body: , status: )
    @body = body
    @status = status
  end

  private

  attr_reader :body, :status

end
```

... and the following template
```slim
.message
  .message__body = body
  .messate__status = status
```

In this scenario, **how should caching be handled?**

I see the following options:

1. Add a caching option to the render method
```ruby
render MessageComponent(body: body, status: status), cached: true
```

2. Cache directly in the template

```slim
- @messages.each do |message|
  - cache message
    = render MessageComponent(body: body, status: status) 
```

3. If I'm getting the arguments part wrong (see beginning of post) and it is OK to pass an object as an argument, then the component's template could handle caching with something like

```slim
- cache message
  .message
    .message__body = body
    .messate__status = status
```

This would also relate to the question on rendering collections #21 
```slim
= render MessageComponent, collection: products, cached: true
```

Thanks in advance!

**Comment by joelhawksley** [comment]
@pinzonjulian it's exciting to hear that components are working well for you on your project!

> By the examples in @joelhawksley 's talk at RailsConf and the examples in the repo, I understood that the arguments you pass to your component should be as lean as possible. I infer it wouldn't be a good practice to pass entire objects (please correct me if I'm getting it wrong).

Honestly, I'm becoming less sure about this as time goes on. I think that it's good to keep interfaces as lean as possible _in general_, but I don't think it's necessarily a bad thing to pass in an entire object. I don't think view components are any different in regards to this than any other Ruby object. 

Said another way: If you have a partial you're replacing with a view component, and that partial relied heavily on being passed an object, I would probably stick to passing in an object if you think it's necessary!

> In this scenario, how should caching be handled?

Honestly, I think all three of these proposals have merit, but I'm not sure if _any_ of them would work at the moment. #1 probably wouldn't, but #2/#3 might.

As the [design philosophy](https://github.com/github/actionview-component#design-philosophy) for this project states, we're trying to make ActionView::Component behave in a manner that is as predictable and consistent with Rails as possible. 

That being said, we should probably support _all_ of these interfaces. If you're up for it, I'd welcome a PR 😍

**Comment by czj** [comment]
We've been using components for a while in our applications. Thanks to all contributors, `ActionView::Component` is really great !

We've been thinking a lot about caching a lot because we use extensively Russian doll caching, and collection caching with Rails' syntax where you pass a Proc as the cache key.

I think we should be able to use components exactly like we use (and cache) partials.

This syntax for caching a collection based on each record would be great :

```slim
= render ProductCardComponent, collection: products, cached: true
```

But if we have a component that uses several named arguments, I don't see how it would work (a collection passed a single record).

We probably should also be able to let the parent template cache collections like we are used to :

```slim
- cache products do
  = render ProductCardComponent, collection: products
```

Same problem here with passing named arguments to the component.

Finally there is the possibility of having a Proc for the cache key like we can today, and another for passing arguments to the component. But that seems not elegant at all.

I don't know if it is feasible but this pseudo code "ok" to me :

```slim
- cache_each products  do |product|
  = render ProductCardComponent, product: product
```

And you could pass a proc for the custom cache key like so :

```slim
- cache_each products, key: -> { |e| [:special_cache_key, e] }  do |product|
  = render ProductCardComponent, product: product
```

Or like this, more like we have in Rails :

```slim
- cache_each products do |product|
  = render ProductCardComponent, product: product, cached: -> { |e| [:special_cache_key, e] }
```

Last idea : implementing the cache key inside the component's class so we don't have to specify anything where we call the component. By default, component's class name + arguments.

Sorry if the ideas are a bit blurry :)
