### ISSUE TITLE
Rails 6.1 html.erb not reloading on changes

### ISSUE THREAD

**Issue by sebyx07** [github/view_component#560]
Hey, I'm using rails 6.1, ruby 2.7.2

When having a component ex

`a_component.rb` and having the template inside `a_component/a_component.html.erb` 
when editing the HTML file, the browser reloads, but the HTML output doesn't change.

Worked before in 6.0.

To trigger the correct reload, I need also to change the `a_component.rb`

**Comment by alexventuraio** [comment]
I do confirm I face the same behavior!
- Rais 6.1.0
- Ruby 2.7.2

Whenever I change the HTML markup in `app/components/notification_component.html.erb` and refresh the browser, changes do not seem to take effect.

To trigger the changes:
- Restart the rails server
- Do any change on any `.rb` file like `application_controller.rb` or `user.rb`, to give some examples.

Is that a expected behavior or there's any way to fix it?

**Comment by joelhawksley** [comment]
@sebyx07 @alexventuraio thank you for the report! This is not the expected behavior. Might you be able to open a PR with a failing test? 

There are existing tests for similar behavior you might be able to reuse bits of: https://github.com/github/view_component/blob/main/test/view_component/view_component_test.rb#L284.

**Comment by kirin121** [comment]
Same issue on Rails 6.1. 
Looks like `ViewComponent::CompileCache.invalidate!`  isn't triggered within reqests(mandatory to clear templates cache).
Manual call of `ViewComponent::CompileCache.invalidate!` in application code during request cycle - helps

**Comment by volodymyr-sh** [comment]
@alexventuraio , @sebyx07,  i just setuped "view_component" on my new Rails app. Templates were always cached.
Then i found that i forgot to do  `require: "view_component/engine"` in Gemfile.
I had ` gem "view_component"` in Gemfile, but correct setup is `gem "view_component", require: "view_component/engine"`
After adding engine require - issue disappeared and i no longer need to do `ViewComponent::CompileCache.invalidate!` manually

**Comment by sebyx07** [comment]
@volodymyr-sh thanks!

**Comment by jrochkind** [comment]
I just ran into this too!  Making sure the `require: "view_component/engine"` was in Gemfile fixed it!

The "failure mode" of forgetting to do this is subtle, everything seems _mostly_ to work, with some odd edge case failures (like this one), that you might not notice, or might not even realize it's broken. 

I wonder if there are other error reports that could be caused by this but nobody realizes?

I wonder if the failure mode can be made "noisier" somehow, so if you forget to do this it's obvious you've made a mistake, instead of just subtle edge-case differences. 

(If loading view__component/engine is optional, there must be a use case for choosing not to do it though? I don't think you can use ViewComponent without Rails at all, so I don't think that's it?  I assume there is a reason to not make loading the engine class forced in all cases though?)

**Comment by Spone** [comment]
@joelhawksley isn't there a way to make the gem work without having to require the engine from the Gemfile?

**Comment by rmacklin** [comment]
One way is [following this](https://github.com/rails/sprockets-rails/blob/118ce60b1ffeb7a85640661b014cd2ee3c4e3e56/lib/sprockets/rails.rb#L2-L4): https://github.com/github/view_component/commit/9268939f06c1d47f312301ba092703940a8102d8

**Comment by rmacklin** [comment]
Perhaps [following this](https://github.com/rails/sprockets-rails/blob/118ce60b1ffeb7a85640661b014cd2ee3c4e3e56/lib/sprockets/rails.rb#L2-L4): https://github.com/github/view_component/commit/9268939f06c1d47f312301ba092703940a8102d8

**Comment by halo** [comment]
That's splendid, thank you for the effort @rmacklin  👍🏻 

I can confirm that this change solves the "reloading HTML" problem.

As a side-note, the following line also fails when the engine was not loaded ("`config.view_component` is not defined").

```ruby
# config/development.rb
config.view_component.preview_paths << Rails.root.join('spec/components/previews')
```

So, the change in your branch would also warrant changing the documentation here, the require can be removed:
https://github.com/github/view_component/blob/69087aaffb79d7c841990926d90edde1a2d3a440/docs/guide/getting-started.md#L22

**Comment by rmacklin** [comment]
Curious to hear from @joelhawksley if there's a reason we haven't been doing this before, or if we should proceed with the change
