### ISSUE TITLE
Deprecate Content Areas

### ISSUE THREAD

**Issue by BlakeWilliams** [github/view_component#620]
Before the 3.0 release we should deprecate content areas suggesting that existing usage is migrated to Slots V2. This will give users of the library time to migrate to slots before the V3 release, which will remove content areas.

part of https://github.com/github/view_component/issues/617

**Comment by dvantuyl** [comment]
Apologies if I'm misunderstanding Slots V2 usage, but it doesn't seem to cover the basic use case where Content Areas allowed multiple named slots:

```ruby
with_content_areas :header, :body
```

This doesn't work since the second arg of renders_one is expecting a class:
```ruby
renders_one :header, :body
```

This also doesn't work as the content in :body is ignored:
```ruby
renders_one :header
renders_one :body
```

Is this a bug? Or is there another way to use renders_one that isn't explained in the documents.

**Comment by BlakeWilliams** [comment]
@dvantuyl The last example should work similar to how content areas work. I think we have test coverage around it via the `SlotsV2Component` in the test suite.

If it's not working, could you open a PR with a failing test?

**Comment by dvantuyl** [comment]
Thank you @BlakeWilliams. After testing around my issue, `SlotsV2Component` are working for the most part with multiple `renders_one`.  `SlotsV2Component` only breaks when the parent template containing the view_component is in HAML. ERB parent templates are working as expected.

I've converted my parent templates to ERB for now and will work on PR with failing HAML tests.

**Comment by joelhawksley** [comment]
Closed by https://github.com/github/view_component/pull/763
