### ISSUE TITLE
ViewComponent needs a logo!

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#649]
### Steps to reproduce

Go to https://blog.cloud66.com/hotwire-viewcomponents-and-tailwindcss-the-ultimate-rails-stack/. 

Look at this picture: 

![image](https://user-images.githubusercontent.com/1940294/109216525-df855880-7771-11eb-8fa9-cb7707af3e2d.png)

Think about how cool it would be if we had a logo!

### Expected behavior

ViewComponent has a logo.

### Actual behavior

We don't.

### References

It might be nice to figure this out as part of https://github.com/github/view_component/issues/505.

**Comment by dylanatsmith** [comment]
Designer-developer checking in. Would love to help out with this.

Have you thought much about possible concepts or anything yet?

**Comment by dylanatsmith** [comment]
I caught up with @joelhawksley earlier today and wanted to drop a few notes from our conversation.

* ViewComponent is currently too plain, but overbranding should also be avoided
* Similarly, branding should be neither too generic nor too distinct; blending in with the ecosystem would be positive
* Litmus test: Does the logo fit alongside other frameworks' logos (as in the screenshot above or on sites like [Storybook](https://storybook.js.org/)?
* Branding should lend an air of maturity and gravitas to the project
* "Building blocks" may be too cliché as a visual metaphor, but could lead to more interesting ideas
* A nod to Ruby would be welcome

**Comment by romashamin** [comment]
Hello everyone from Martian designers! @palkan shared a link and asked us whether we can help here.

As a quick idea, we could take a ruby, split it into two pieces, and get styled V and C. Like this:
![ViewComponent Logo Idea](https://user-images.githubusercontent.com/1148914/114770803-851d7700-9d74-11eb-8116-2e33644644e3.png)

The result is close to the building blocks idea cause we actually assemble the logo from parts. And it’s a hidden link to Ruby, as you wanted 🙂

What do you think?

**Comment by joelhawksley** [comment]
@romashamin thanks for taking a crack at the VC logo! This is a fun concept.

I wonder how it might look at smaller sizes, such as a favicon or added to this list on the Storybook site:

<img width="202" alt="Screen Shot 2021-04-15 at 12 44 48 PM" src="https://user-images.githubusercontent.com/1940294/114922091-87211d80-9de8-11eb-9eb5-44f1a73cef9c.png">

**Comment by romashamin** [comment]
@joelhawksley for example:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/1148914/114992495-800b1580-9ea3-11eb-9ad6-d1c32e908d50.png">

The geometric nature of the logo accurately fits a pixel grid in favicon sizes:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/1148914/114993048-12abb480-9ea4-11eb-9f3c-9798d4108493.png">

**Comment by boardfish** [comment]
There's something unsatisfying about the difference in heights and angles. The C looks too tall to be a C.

Does it look any better if you position what you've got there like this?

![image](https://user-images.githubusercontent.com/20680337/115034960-f6b80b00-9ec3-11eb-92df-d3f2c17fdec0.png)

**Comment by BlakeWilliams** [comment]
I like the inspiration and idea behind the logo! 

I have a few thoughts though. I agree with @boardfish about the proportions. I think the V is much wider than a standard V and the C is also a bit short width wise which I think throws off some of the balance. I also find it a bit difficult to distinguish in the smaller formats.

Unrelated to any specific design, In my mind, view components are all about encapsulating your views (translations, CSS, JS, logic, etc.) so maybe there's some inspiration to be found there as well?

**Comment by boardfish** [comment]
I was thinking about this just now and scribbled up an idea. It'd be nice to have the point of the gem representing a V somehow, but I figured we could make a C from the outline. In a way, I feel like that sort of represents the encapsulation `view_component` gives, because it almost completely surrounds the gem here. 

![Screenshot_20210417-075430_Keep_notes.png](https://user-images.githubusercontent.com/20680337/115104718-37f6fc00-9f52-11eb-89fe-8e81becb409c.png)

**Comment by dylanatsmith** [comment]
A few observations on the above:

Ruby's gem shape is very simple, sturdy, and balanced. The concepts riffing off that come from an interesting place but, by nature of deconstructing the gem, we immediately lose the qualities that make it work so well.

Taking a look at the list of framework logos, there are many commonalities. Many are similarly "sturdy" to the gem shape above, and many are symmetrical or at least the visual weight is very balanced. There's something to learn from that.

Also worth noting that many share similar shapes. Angular, HTML5, Web Components, Marko, Preact, and Stimulus all have hexagonal angles or badge-type shapes reminiscent of a gem. Given the thoughts about "fitting in" with the framework ecosystem, this might be something to lean into _or_ an opportunity to buck that trend (a la Tailwind's curves) if there's no way to keep it fresh.

**Comment by dylanatsmith** [comment]
Inspired by the above, I was playing around with gem shapes and stumbled on this direction.

A typical illustration of a gem from a top perspective...

<img width="120" alt="image" src="https://user-images.githubusercontent.com/6905903/115251410-6e837100-a122-11eb-821a-5c25c6398e43.png">

...with lines added to create a central box shape (representing building blocks, encapsulation, etc)...

<img width="120" alt="image" src="https://user-images.githubusercontent.com/6905903/115251466-7fcc7d80-a122-11eb-86b7-5e3c49648e23.png">

...then other lines removed to leave an abstract box in the corner of a room.

<img width="120" alt="image" src="https://user-images.githubusercontent.com/6905903/115251557-9246b700-a122-11eb-8b5b-c9c0e172341e.png">

I played around with a bunch of slight variations on this. It's starting to feel like I took the scenic route to creating a generic box but maybe someone with fresh eyes can chime in. Any threads worth pulling on?

<img width="680" alt="image" src="https://user-images.githubusercontent.com/6905903/115258793-36cbf780-a129-11eb-8c04-75ad75150512.png">

**Comment by boardfish** [comment]
You might've accidentally recreated Webpack there. :joy: 

![image](https://user-images.githubusercontent.com/20680337/115264056-e2774680-a12d-11eb-9c1c-2324b6016196.png)

**Comment by dylanatsmith** [comment]
At least I feel validated. 😂

**Comment by dylanatsmith** [comment]
I played around with a bunch more hexagon explorations, mostly turning them into the letter V. Is this anything?

![image](https://user-images.githubusercontent.com/6905903/121417042-621cd700-c961-11eb-9bc7-14d87edcd868.png)

**Comment by boardfish** [comment]
I'm a fan of the Tall V ones, especially because of the implicit V for ViewComponent, hexagonal shape and diamond on the right that both allude to Ruby.

**Comment by dylanatsmith** [comment]
That's probably how I would have pitched this if I was trying to convince a client haha. Nicely done.

The diamond was a happy accident; I didn't notice it until I read your comment. I like that, though, and for that reason I'm more drawn to the versions on the right side of that row. The gap highlights the shape. My implementation, however, skews the diamond so here are a few adjusted versions that preserve it.

![image](https://user-images.githubusercontent.com/6905903/121511474-95eb1180-c9e0-11eb-98f0-c169af89b91a.png)

I think I'm most drawn to the versions in the left two rows right now (two-tone red and the solid, single-colour variants). Something in me really wants the rounded versions to work but I'm worried they make the diamond look a bit awkward sat beside the left section.

There's something about the flat edge on the bottom in these versions that makes it feel "sturdy" as well. It takes up more of a square compared to the "Wide V" explorations. Both feel like you can view them as some allusion to a box as well. But the "Box" explorations are probably still too close to my earlier ideas and thus Webpack et al?

Just for fun, here's what the "Tall" versions would look like with the diamond turned into a gem.

![image](https://user-images.githubusercontent.com/6905903/121513411-bb791a80-c9e2-11eb-80d0-c500eb71df2e.png)

The bottom ones are kind of neat — part hexagon, part checkmark, overt Ruby reference, and almost a V. But maybe trying to do too much?

@nshki mentioned a similarity between the "Tall V" style and [GitLab's logo](https://about.gitlab.com/images/press/logo/jpg/gitlab-logo-gray-stacked-rgb.jpg). I personally don't think it'd be too close to worry about confusion, especially in contexts where the ViewComponent is likely to be used.

![image](https://user-images.githubusercontent.com/6905903/121509107-3855c580-c9de-11eb-994c-c254d85b5295.png)

In the above, I think the closest logo is actually Angular, mostly because of their use of two-tone cherry colouring in a shield shape. The giant "A" clear things up quite a bit, though. Using any colour other than deep red — or at least not incorporating it as an accent in some way — would do a pretty big disservice to the goal of associating with the Ruby ecosystem.

**Comment by dylanatsmith** [comment]
A few more pulling on the same thread:

![image](https://user-images.githubusercontent.com/6905903/121531576-74952000-c9f6-11eb-811d-7ac5fd35161f.png)

The wider gap seems to distance this version from any of the similar logos mentioned so far, and also emphasises the diamond shape. Scales down well, too.

Something about this is making me look for a shape or letter in the negative space, though, that isn't there. For example, a slight modification makes it look like a white `U` shape with dark shadows:

![image](https://user-images.githubusercontent.com/6905903/121532332-26cce780-c9f7-11eb-9f61-a50aa79e7c6f.png)

Here's another direction playing on the diamond idea. This is sort of like "moving Ruby forward" with the arrows. We lose the "V" idea.

![image](https://user-images.githubusercontent.com/6905903/121537807-2aaf3880-c9fc-11eb-8a1c-5bdda95ba61e.png)

The leftmost and rightmost concepts are probably too generic but I kind of like the box-looking #2 and box/chevron #3. #2 doesn't play well as a single colour, so might struggle in situations like Joel's initial screenshot at the top of the thread.

**Comment by dylanatsmith** [comment]
One good thing about these shapes is that they're super quick to iterate on. 😅

![image](https://user-images.githubusercontent.com/6905903/121673614-fba2d080-caa8-11eb-9c28-9ee17b889668.png)

I'd love to hear what everyone's thoughts are so far.

To reiterate the direction discussed earlier:

> - ViewComponent is currently too plain, but overbranding should also be avoided
> - Similarly, branding should be neither too generic nor too distinct; blending in with the ecosystem would be positive
> - Litmus test: Does the logo fit alongside other frameworks' logos (as in the screenshot above or on sites like Storybook)?
> - Branding should lend an air of maturity and gravitas to the project
> - "Building blocks" may be too cliché as a visual metaphor, but could lead to more interesting ideas
> - A nod to Ruby would be welcome


Some feedback prompts:
- Are any versions standing out as particularly strong visually?
- Do you feel strongly (positively or negatively) about any particular visual concepts?
  - Hexagonal shape
  - Box metaphor
  - Abstract letter V
  - Arrows
  - Diamond
- If you don't think we're there yet, why not? Is there something about logos you like that you think we're missing?
- Do we think some shade of Ruby red is the right colour?

**Comment by boardfish** [comment]
> * Are any versions standing out as particularly strong visually?

I'm a fan of the last one you posted, particularly the version that's in the sidebar. The thing I like about this one is that the negative space sort of implies that it's the top-right corner of a ruby, and the chevron also sort of represents ViewComponent as a component that extends Ruby. However, as I'll go on to mention, the hexagon style means this feels a bit less original.

I also like [this one](https://github.com/github/view_component/issues/649#issuecomment-858647336) - it feels the most original and the diamond as an allusion to Ruby is very strong, but the negative space in the other one I've talked about here makes it a lot stronger at a smaller size.

>  * Do you feel strongly (positively or negatively) about any particular visual concepts?
>     * Hexagonal shape
>     * Box metaphor

I'm on the fence about both of these, since they feel like they've been used a lot in the tech space in general.

>    * Abstract letter V

I like this idea, but I think it's quite hard to execute well. It's the kind of thing we could definitely look to include in negative space, or a C.

>    * Arrows

These have some potential, but I'm not sure they're as exciting as a diamond.

>    * Diamond

Strongly in favor of including this, or all or part of some other gem as a Ruby allusion.

> * If you don't think we're there yet, why not? Is there something about logos you like that you think we're missing?

I feel like we're much closer, especially thanks to the work you've done here. :sparkling_heart: But I personally don't feel huge attachment to what's here so far.

> * Do we think some shade of Ruby red is the right colour?

I think we should be careful not to close off options by getting too attached to it, but it looks great in what we've seen so far.

<details>
  <summary>If you want to answer these questions more easily, copy this template:</summary>

```
> * Are any versions standing out as particularly strong visually?
>  * Do you feel strongly (positively or negatively) about any particular visual concepts?  
>     * Hexagonal shape
>     * Box metaphor
>     * Abstract letter V
>     * Arrows
>     * Diamond
>   * If you don't think we're there yet, why not? Is there something about logos you like that you think we're missing?
>   * Do we think some shade of Ruby red is the right colour?
```
</details>

**Comment by jaredcwhite** [comment]
> A few more pulling on the same thread:
> 
> ![image](https://user-images.githubusercontent.com/6905903/121531576-74952000-c9f6-11eb-811d-7ac5fd35161f.png)

FYI, just happened to notice this today…
![C7238B21-6F24-4CC7-99ED-F9D7ACD421BE](https://user-images.githubusercontent.com/658496/121760418-7e468280-cadf-11eb-9b5a-c47b71b42583.jpeg)

FWIW, I like the latest set of 3D boxes and lines of negative space.

**Comment by dylanatsmith** [comment]
> FYI, just happened to notice this today…

Nice catch, @jaredcwhite. Really helpful to have lots of people familiar with other logos to prevent a parallel thinking accident.

**Comment by joelhawksley** [comment]
Wow! Thank you all for your feedback and to @dylanatsmith for the design iterations.

As I'm not a designer myself, I enlisted the eye of several designer colleagues for reviewing what we have so far. We came to the agreement that this option is the strongest:

<img width="436" alt="Screen Shot 2021-06-21 at 10 34 10 AM" src="https://user-images.githubusercontent.com/1940294/122798073-61e3dc00-d27d-11eb-8ab7-22ae5626fb28.png">

Here's why we like it:

- The arrow created by the negative space reads clearly, even at a small size. It reads most clearly pointing right, not upwards or downwards.
- The parallelogram (leftmost form) reads like a gem, a nice nod to ViewComponent's Ruby nature. 

@dylanatsmith would you be willing to provide some explorations around shading, rounding, and any other permutations you might want to consider?

**Comment by dylanatsmith** [comment]
Thanks @joelhawksley, appreciate the thought that went into that review. I agree with those points.

With shape narrowed down I should be able to explore some additional options inside of the next two weeks and add them here for consideration.
